server:
  port: 8085
  
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/09sbms
    username: root
    password: root